name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sec:
    name: Sec
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Set .netrc
        run: echo machine github.com login d-darac password ${{ secrets.PAT }} > ~/.netrc

      - name: Set GOPRIVATE
        run: export GOPRIVATE=github.com/d-darac/inventory-assets

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec -exclude-generated ./...

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Set .netrc
        run: echo machine github.com login d-darac password ${{ secrets.PAT }} > ~/.netrc

      - name: Set GOPRIVATE
        run: export GOPRIVATE=github.com/d-darac/inventory-assets

      - name: Run unit tests
        run: go test ./... -run Unit -cover

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    env:
      DB_TEST_URL: ${{ secrets.DB_TEST_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run postgres docker container
        run: docker run --name inventory-test -e POSTGRES_PASSWORD=${{ secrets.DB_TEST_PASSWORD }} -e POSTGRES_USER=${{ secrets.DB_TEST_USERNAME }} -p 5432:5432 -d postgres

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Set .netrc
        run: echo machine github.com login d-darac password ${{ secrets.PAT }} > ~/.netrc

      - name: Set GOPRIVATE
        run: export GOPRIVATE=github.com/d-darac/inventory-assets

      - name: Run Database Migrations
        run: ./scripts/migrateup.sh

      - name: Run integration tests
        run: go test ./... -run Integration -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Set .netrc
        run: echo machine github.com login d-darac password ${{ secrets.PAT }} > ~/.netrc

      - name: Set GOPRIVATE
        run: export GOPRIVATE=github.com/d-darac/inventory-assets

      - name: Format code
        run: test -z $(go fmt ./...) && echo $?

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
